on:
  push:
    branches:
      - main
  # run it on push to the default repository branch

env:
  GITHUB_SHA: ${{ github.sha }}
jobs:
  ui-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: yarn install

      - name: Build the ui
        run: yarn run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.PROD_GCP_WEBSITE_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Setup project'
        run: 'gcloud config set project website-372116'

      - name: 'Upload logo files'
        run: 'gsutil -m cp -r build/** gs://arkiter.com'